### ISSUE TITLE
Publishing Status

### ISSUE THREAD

**Issue by a6dang** [TypeFox/monaco-languageclient#313]
Hello. I was curious as to what the status is for this project. The last published version on the NPM registry is 0.13.0; however, there's been several updates since then that I'd be interested in using. I also noticed this package - https://www.npmjs.com/package/@codingame/monaco-languageclient which seems to be publishing the updates and is linked to this repo as well.

Is the preference here to use that package or is it possible to get a new version published here: https://www.npmjs.com/package/monaco-languageclient?

Thanks

**Comment by CGNonofr** [comment]
Hello!

The original maintainers of this project are not active anymore. I don't have access to their npmjs package and the automated workflows are broken.

I now publish every update to `@codingame/monaco-languageclient`. I plan to mark this repo as deprecated, switch to a CodinGame github repo and automated everything again, but it takes time. It's gonna happen eventually as soon as I manage to get some time to do it.

**Comment by spoenemann** [comment]
Hi @CGNonofr! Firstly, thank you very much for maintaining this code!

I'm sorry for the long silence from TypeFox regarding this repository. Let me try to explain.

The initial motivation for the development of monaco-languageclient was to have direct support for language servers in [Theia IDE](https://theia-ide.org/), which uses Monaco as its text editor. With [version 1.4.0](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md#v140---30072020) published in July 2020, this language server support was deprecated in favor of the VS Code extension API. This meant that monaco-languageclient was no longer needed for that project, and we stopped contributing to it because there were loads of other pressing topics at the time (we developed [Gitpod](https://www.gitpod.io/), which was later moved to a separate company).

We would like to get back to contributing to this project. We see Monaco editor being increasingly used within all sorts of web applications, not only web IDEs like Theia. Initially our contributions will be done mainly by @kaisalmen, but others from our team may join as well.

I think it would be beneficial for this project and the community around it to avoid fragmenting the source in multiple active forks. @CGNonofr would you agree in continuing to maintain monaco-languageclient in this repo together with us? If you're interested, I can give you access to publish the original [monaco-languageclient](https://www.npmjs.com/package/monaco-languageclient) package, but of course you can continue publishing to `@codingame/monaco-languageclient` if you prefer that.

In any case, we want to publish up-to-date versions of the `monaco-languageclient` package. @CGNonofr do you see any chance in identifying the git commits from which you published the eight versions from `0.14.0` to `0.17.3`? There are no git tags for those versions, and the `package.json` version number in the source is still at `0.13.0`. If there's no way to recover that information, we'll just publish the latest version, but it would be great to have the previous versions as well.

**Comment by CGNonofr** [comment]
Hello @spoenemann!

It's great news!

I'm fine with publishing to the `monaco-languageclient` package only, the only reason I was publishing it to `@codingame/monaco-languageclient` was the permissions.

I think I didn't do a great job tagging differents releases, we can probably identify them by hands, there's isn't a ton of commits.

I'm ok to with getting npmjs permissions but I think the first step is to fix the automated workflows

**Comment by spoenemann** [comment]
> I'm fine with publishing to the `monaco-languageclient` package only, the only reason I was publishing it to `@codingame/monaco-languageclient` was the permissions.

Great! Do I see correctly that your npmjs.com username is `nonofr`? In order to get publishing access, you need to enable two-factor-authentication.

> I think I didn't do a great job tagging differents releases, we can probably identify them by hands, there's isn't a ton of commits.

**Comment by CGNonofr** [comment]
> Great! Do I see correctly that your npmjs.com username is nonofr?

Correct!

> In order to get publishing access, you need to enable two-factor-authentication.

Done :heavy_check_mark: I should have done it a long time ago

**Comment by kaisalmen** [comment]
@CGNonofr I want to take the opportunity and say hello.

Like @spoenemann said I will the be the first from the TypeFox team to contribute and help here again. I started to work on topics regarding monaco-editor quite recently and we started to work on web components around `monaco-editor` and `monaco-languageclient` this year (https://github.com/TypeFox/monaco-components not yet released on npm) and we agreed that I should start to contribute here and we stop the being silent.

As you said getting everything going again is needed. I propose to open an issue about this topic (release workflow, changelog,  tags, etc.)

**Comment by CGNonofr** [comment]
Hello :hand: 

> As you said getting everything going again is needed. I propose to open an issue about this topic (release workflow, changelog, tags, etc.)

good idea :+1: 

Some more stuff for the backlog:
- The `examples/browser` is confusing people since it doesn't use the whole lib but only the converters
- Some tools/libraries are now quite old (typescript for instance)
- A new monaco-editor version was released, we should check the compatibility

**Comment by kaisalmen** [comment]
> Some more stuff for the backlog:

Yes, reconnecting web socket is also a topic where I was asking myself if it could/should be done differently

> A new monaco-editor version was released, we should check the compatibility

Here I also need to "learn" how to analyse changes and adapt here

**Comment by CGNonofr** [comment]
> Yes, reconnecting web socket is also a topic where I was asking myself if it could/should be done differently

You're right, I ended up not using it and writing my own implementation (there is already restart policy in vscode-languageclient, I don't thing we need a websocket reconnect lib)

> Here I also need to "learn" how to analyse changes and adapt here

When there is breaking changes, typescript tells it, then I usualy  just run it on the most complete language server I know and test all features

**Comment by martypitt** [comment]
Hi.  I wanted to chime in and add my excitement to this issue.  We're using this (and the codingame fork) in our app, and  and have found it tough.  I was checking the issues today because I was worried this had become abandoned.  

I'm thrilled to see that this repo will start getting some love again, and am really grateful to the people who take time to maintain it - in whatever capacity - Thank you @kaisalmen , @CGNonofr and @spoenemann.

I wish I could offer to help (I don't have the time), I'd be glad to sponsor or contribute in a way that isn't coding related.  (Fond wishes?)

**Comment by spoenemann** [comment]
Thanks @martypitt! @kaisalmen and I work at https://www.typefox.io offering consulting for open source libraries and frameworks. If there's anything you'd like to see improved in short term, sponsoring that work is definitely an option. You're welcome to contact me: miro.spoenemann@typefox.io

**Comment by kaisalmen** [comment]
Publishing was successfully revived! 🎉 Let's close this.
