### ISSUE TITLE
Access "window/showMessage" parameters

### ISSUE THREAD

**Issue by mpociot** [TypeFox/monaco-languageclient#327]
In my application, I would like to access / listen to certain methods that the language client receives.
In particular the `window/showMessage` events. It seems like these are by default redirected to console.log, but I would like to manually handle them and display these messages in my UI.

```
{
    "method": "window\/showMessage",
    "params": {
        "type": 3,
        "message": "Indexed 500\/9784 (5.11%) 57\/1,611 mb"
    },
    "jsonrpc": "2.0"
}
```

I couldn't find an easy way how to overwrite this behavior. 
Is this possible?

**Comment by CGNonofr** [comment]
Instead of calling `MonacoServices.install`, you can call `Services.install` directly which takes the services as parameter (see https://github.com/TypeFox/monaco-languageclient/blob/master/client/src/monaco-services.ts)

doing so, you can use you own `window` service and implement the `showMessage` method as you wish

**Comment by mpociot** [comment]
Perfect, thanks again for the super-fast response!
