### ISSUE TITLE
How to disable features like 'textDocument/formatting'.

### ISSUE THREAD

**Issue by tyagirajat200** [TypeFox/monaco-languageclient#393]
How we can disable the features like 'textDocument/formatting'. This message is being send to language server to format the document.

**Comment by CGNonofr** [comment]
May I know what is the use case?

You can extend MonacoLanguageClient to override the registerBuiltinFeatures method. You'll need to copy everything except your feature though, it's not very convenient.

You can also probably disable it on the server side

**Comment by tyagirajat200** [comment]
So the JAVA LSP https://github.com/georgewfraser/java-language-server that we are using has some issues wrt document formatting that it breaks the lsp when formatting the code, we need to disable that feature only for JAVA.
Can you provide some examples of how I can override the built-in features?

**Comment by CGNonofr** [comment]
Your best option is to disable the feature on the language server itself, I don't know if the option exists

Otherwise, just duplicate [this method](https://github.com/TypeFox/monaco-languageclient/blob/fbc2f1e314264f6aa092ed35faeb7cb31131aa6b/packages/client/src/monaco-language-client.ts#L119) and remove the formatting features

**Comment by tyagirajat200** [comment]
Got it thanks
