### ISSUE TITLE
monaco-converter removal

### ISSUE THREAD

**Issue by char0n** [TypeFox/monaco-languageclient#419]
Hi, 

Thanks for all the work. 

I'd like to ask about reasons why `monaco-converter` module was removed from this library. There is currently no real alternative I could find. The CHANGELOG tells us to look into [language service written in JavaScript](https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/browser/src/client.ts). I did try to use [vscode-languageclient](https://www.npmjs.com/package/vscode-languageclient) and [@codingame/monaco-vscode-api](https://www.npmjs.com/package/@codingame/monaco-vscode-api) in [this experiment](https://github.com/swagger-api/swagger-editor/commit/ea3c67306815b138aed7d9b1680b35b62e4daa1d). After while I figure out that shapes the [vscode-languageclient](https://www.npmjs.com/package/vscode-languageclient) is producing is incompatible with monaco editor and additional transformations needs to be done. By removing `monaco-converter` from this library there is no backward compatible solution using just [vscode-languageclient](https://www.npmjs.com/package/vscode-languageclient) and [@codingame/monaco-vscode-api](https://www.npmjs.com/package/@codingame/monaco-vscode-api).

Can you maybe elaborate about why `monaco-converter` was removed? Thanks you!

![image](https://user-images.githubusercontent.com/193286/190134711-1407cda9-109d-48ba-8312-11d4de57eeb9.png)

Refs https://github.com/swagger-api/swagger-editor/pull/3449

**Comment by char0n** [comment]
CC @CGNonofr as he would be possible able help as well.

**Comment by CGNonofr** [comment]
Hello,

The removal shouldn't impact you except if you're registering language features by hands. If you're just using a `LanguageClient`, there's no reason to bother about it.

You should have a look at the history section of [monaco-vscode-api](https://github.com/CodinGame/monaco-vscode-api#history)

TL:DR:
- The `monaco-converter` was there to transform `LSP` objects to `Monaco` objects
- `vscode-languageclient` already contains converter from `LSP` objects to `vscode` objects
- `monaco-vscode-api` is able to handle `vscode` objects

So I suggest you use `vscode.languages.registerXXX` instead of `monaco.languages.registerXXX` while using the converter from `vscode-languageclient` like you did

**Comment by char0n** [comment]
Hi @CGNonofr, thanks for quick answer.

> The removal shouldn't impact you except if you're registering language features by hands

That's exactly what I'm doing unfortunately: https://github.com/swagger-api/swagger-editor/blob/c37b4ac78e3c9e97e134be7a29b41bfe3e2a32ca/src/plugins/editor-monaco/workers/apidom/apidom-mode.js

We're using `monaco-editor-core` and plug language features by hand.

> You should have a look at the history section of [monaco-vscode-api](https://github.com/CodinGame/monaco-vscode-api#history)

Yes, I've read it very carefully. But nothing that is written there helps my situation, and that's `monaco-converter` is missing.

> So I suggest you use vscode.languages.registerXXX instead of monaco.languages.registerXXX while using the converter from vscode-languageclient like you did

This just doesn't work. Editors stops working and I'm getting:

![image](https://user-images.githubusercontent.com/193286/190143998-4948c3b5-13dd-4e09-9e0d-a4b7c6f701f0.png)

**Comment by CGNonofr** [comment]
You usually get this error when there is multiple versions of monaco-editor in the project.

You said that you are using `monaco-editor-core` while `monaco-editor` is imported from monaco-vscode-api

Just make sure you only have a single version of monaco-editor/monaco-editor-core in your node_modules and it should be fine. You may need to use aliases or switch to `monaco-editor` instead of `monaco-editor-core`

**Comment by char0n** [comment]
> You usually get this error when there is multiple versions of monaco-editor in the project.

I checked and even created webpack `resolve.alias`, but still the same error.

> You said that you are using monaco-editor-core while monaco-editor is imported from monaco-vscode-api

Yes, for many reasons we decided to use `monaco-editor-core` and not `monaco-editor`. I noticed monaco-vscode-api is using monaco-editor so that means that we're pulling `monaco-editor` into the bundle as well, right?

> Just make sure you only have a single version of monaco-editor/monaco-editor-core in your node_modules and it should be fine.

I'm sure, I even manually checked package-lock.json file. The error is still there.

**Comment by kaisalmen** [comment]
I just checked to be sure: The difference between  `monaco-editor-core` and `monaco-editor` is the it exports language namespaces (basic languages, ts, css, json, html) in addition to the API in the d.ts., but the actual content of `editor.all.js` and `editor.api` is identical => no need for `monaco-editor-core` IMO if max. need these two imports.

**Comment by kaisalmen** [comment]
@char0n Please test: monaco-languageclient@4.0.1-next.0
It exposes `monaco-converter` again. If that work for you I will release 4.0.1 and we let's find another solution afterwards. Sounds good?

**Comment by char0n** [comment]
> I just checked to be sure: The difference between `monaco-editor-core` and `monaco-editor` is the it exports language namespaces (basic languages, ts, css, json, html) in addition to the API in the d.ts., but the actual content of `editor.all.js` and `editor.api` is identical => no need for `monaco-editor-core` if you max. need these two imports IMO.

Technically you're right, we just followed the recommendation from Microsoft and used `monaco-editor-core` as we fell within it's definition of usecases.

**Comment by char0n** [comment]
> @char0n Please test: monaco-languageclient@4.0.1-next.0 It exposes `monaco-converter` again. If that work for you I will release 4.0.1 and we let's find another solution afterwards. Sounds good?

Works like a charm: https://github.com/swagger-api/swagger-editor/pull/3463. Thanks a lot

**Comment by char0n** [comment]
Regarding finding alternative solution for `monaco-converter`:

I was thinking that in webpack alias I could alias `monaco-editor` as `monaco-editor-core`, and given that [@codingame/monaco-vscode-api](https://www.npmjs.com/package/@codingame/monaco-vscode-api) uses only apis from both packages that compatible, it should probably work. Do you have any other suggestions?

**Comment by kaisalmen** [comment]
> Technically you're right, we just followed the recommendation from Microsoft and used monaco-editor-core as we fell within it's definition of usecases.

`monaco-editor-core` was just here before, but it introduces problems when dependent projects use `monaco-editor`. That's why we moved to `monaco-editor` before 1.0.0 release and before `monaco-vscode-api` was started by @CGNonofr.  When you just use the "basic" imports then tree-shaked bundles should be the same. You now face the issue the other way around.

> I was thinking that in webpack alias I could alias monaco-editor as monaco-editor-core, and given that [@codingame/monaco-vscode-api](https://www.npmjs.com/package/@codingame/monaco-vscode-api) uses only apis from both packages that compatible, it should probably work. Do you have any other suggestions?

You can try to trick it in the `package.json` by adding  `"monaco-editor-core": "npm:monaco-editor@0.34.0"` as dependency.

> Works like a charm: https://github.com/swagger-api/swagger-editor/pull/3463. Thanks a lot

I will do a regular 4.0.1 release soon.

**Comment by CGNonofr** [comment]
I'm not sure of the point of bringing it back, can't they just use the last version of monaco-languageclient that includes it? it's very deprecated

**Comment by kaisalmen** [comment]
Yes, but it was maybe a bit surprisingly removed by me. The code now has a @depcrecated notice (#420). It will be gone with the next major release. I also don't see the need to further maintain the code.

**Comment by kaisalmen** [comment]
@char0n I have looked at the swagger-editor repository and come to the conclusion that you actually don't need **monaco-langaugeclient** and can directly rely on [@codingame/monaco-vscode-api](https://www.npmjs.com/package/@codingame/monaco-vscode-api) in your current architecture. I interpret [#3469](https://github.com/swagger-api/swagger-editor/issues/3469) in this way (you created it while I was looking at the project).

For the time being you can use monaco-languageclient `4.0.1-next.0` or `3.0.1`. I think it will make no fundamental difference for **swagger-editor** because both use monaco-editor 0.34.0. We decided to not bring back the converter as it was marked deprecated since 2.0.0.

Isn't using 'vscode-languageserver-protocol/browser' an option for you project, see [browser-lsp example](https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/browser-lsp/src/client.ts)? You can rely on the browser protocol version and implement a full language server in a worker. We do this in langium as well: https://langium.org/showcase/statemachine/

**Comment by char0n** [comment]
> @char0n I have looked at the swagger-editor repository and come to the conclusion that you actually don't need monaco-langaugeclient and can directly rely on [@codingame/monaco-vscode-api](https://www.npmjs.com/package/@codingame/monaco-vscode-api) in your current architecture. I interpret https://github.com/swagger-api/swagger-editor/issues/3469 in this way (you created it while I was looking at the project).

Yep, I figured that out during yesterday evening. I've just pushed additional commit to the `monaco-converter` branch: https://github.com/swagger-api/swagger-editor/tree/char0n/monaco-converter

Unfortunately things don't work as before. We'll have to adapt some code - I'm still figuring it out what needs to be changed.

> For the time being you can use monaco-languageclient 4.0.1-next.0 or 3.0.1. I think it will make no fundamental difference for swagger-editor because both use monaco-editor 0.34.0. We decided to not bring back the converter as it was marked deprecated since 2.0.0.

All right, thanks.

**Comment by char0n** [comment]
Thanks for all the help, I'm slowly figuring out adaptations for the code.

**Comment by char0n** [comment]
I've managed to adapt the codebase in this PR: https://github.com/swagger-api/swagger-editor/pull/3475/files

I'll do some more testing, and after that we should no longer need the `monaco-converter`. 

I'm also sorry we won't be using `monaco-languageclient` anymore ;]

**Comment by char0n** [comment]
One additional note: To mimic as if `monaco-editor-core` is installed instead of `monaco-editor` one can use following webpack config:

```js
resolve: {
  alias: {
    // This doesn't pull any languages into bundles and works as monaco-editor-core was installed
    'monaco-editor$': 'monaco-editor/esm/vs/editor/edcore.main.js',
  }
}
```

`edcore.main.js` entrypoint contains exactly the same stuff that is exported from `monaco-editor-core`.

**Comment by kaisalmen** [comment]
@char0n thanks for the hint. I have created an issue, because we wanted to add a troubleshooting section to the README and this could go there as well.

**Comment by CGNonofr** [comment]
FYI, you can also keep `monaco-editor-core` and use something like

```typescript
resolve: {
  alias: {
    // This doesn't pull any languages into bundles and works as monaco-editor-core was installed
    'monaco-editor$': 'monaco-editor-core$',
    'monaco-editor/': 'monaco-editor-core/',
  }
}
```

OR

just install monaco-editor-core as monaco-editor: `npm install monaco-editor@npm:monaco-editor-core`
