### ISSUE TITLE
One LSP server instance to support multiple monaco clients.

### ISSUE THREAD

**Issue by shoorlyne** [TypeFox/monaco-languageclient#94]
Currently if I start multiple Monaco clients pointing to a clangd LS service, multiple clangd instances will be spawned on the server, with each clangd instance handling one Monaco clients.

For the sake of resource efficiency, is it possible to have only one clangd instance to handle multiple Monaco clients? In my scenario, all clients share the same C++ libraries, and the only difference is the C++ source file being edited. Therefore, it's not desired to spawn a resource hog for new clients other than the first one.

**Comment by akosyakov** [comment]
Do you mean you start multiple language clients even for one page? You don't need to do it. `MonacoWorkspace` can handle several opened filed and one instance of one language client is enough.

**Comment by shoorlyne** [comment]
@akosyakov, thanks for your response :)

Let me provide more info about the context:

Our product allows multiple users (potentially 100+) to edit C++ code at the same time, while providing them with code intelligence via LSP. The content in each user's file is different. All the users share exactly the same C++ environment, including the compiler/linker, boost library, etc. From the language server's perspective, the users only differ in the files they are editing, while everything else is the same. 

Therefore, if I can have one language server instance to handle LSP requests from all the users, it would be more resource efficient. My reasoning: each language server must allocate some resources for AST reading/cache, etc., and with multiple server instances, such effort is duplicated and the resources are wasted.

Last time I checked, a clangd instance started by editing a C++ source file of several lines of code consumed ~50MB. If there are 100 concurrent users, it would be ~5GB. The difference is obvious.

You mentioned `MonacoWorkspace` can handle multiple clients with just one server instance -- how can I achieve this? My experience is different: each time I open a new page to edit C++ code, a new clangd instance is spawned, taking away 50MB of memory.

**Comment by akosyakov** [comment]
Sorry, I misunderstood you, in this case, `MonacoWorkpace` won't be of any help since it is a client-side only to support multiple files for the same user. 

It is a generic question about language servers, you can ask here as well: https://github.com/Microsoft/language-server-protocol. Maybe someone one did something like that.

I could imagine that you can try to build a proxy LS which gets started and initialized on the web server startup, then it manages client connections and delegates their requests to clangd when necessary. You should be aware though that the specification is designed for a server per a single client and it could be that several clients using the same server can affect each other in case of clangd. Please ask it there.

**Comment by amarnath-mishra** [comment]
@shoorlyne were you manage to do this, I mean the memory issue on multiple clients using same resource, please reply ASAP, as I am also facing the same issue.
